repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.0
    hooks:
      - id: gitleaks
        args: ["--redact"]

  - repo: local
    hooks:
    - id: gradle-compile
      name: Gradle compile (Windows safe)
      entry: cmd
      args: ["/c", "gradlew.bat", "compileJava", "-x", "test", "--no-daemon"]
      language: system
      pass_filenames: false
